version: '3.8'

#RUN prepare.sh before this

networks:
  monitoringstack:
    driver: bridge


services:


#DB
  database_compose:
    container_name: database_compose
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - ./init/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      monitoringstack:
    restart: always


#ZABBIX
  zabbix_be:
    container_name: zabbix_compose_be
    image: zabbix/zabbix-server-pgsql
    environment:
      DB_SERVER_HOST: database_compose
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
    - 10051:10051
    networks:
      monitoringstack:
    restart: always


  zabbix_fe:
    container_name: zabbix_compose_fe
    image: zabbix/zabbix-web-apache-pgsql
    environment:
      DB_SERVER_HOST: database_compose
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      PHP_TZ: Europe/Warsaw
    ports:
    - 8732:8080
    networks:
      monitoringstack:
    restart: always
#Guacamole


  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      monitoringstack:
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw


  guacamole:
    container_name: guacamole_compose
    depends_on:
    - guacd
    - database_compose
    environment:
      GUACD_HOSTNAME: guacd_compose
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: database_compose
      POSTGRES_PASSWORD: 'test'
      POSTGRES_USER: postgres
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      monitoringstack:
    ports:
    - 8080/tcp
    restart: always


  nginx:
    container_name: guacamole_compose_nginx
    restart: always
    image: nginx
    volumes:
    - ./nginx/templates:/etc/nginx/templates:ro
    - ./nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
    - ./nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
    ports:
    - 8443:443
    links:
    - guacamole
    networks:
      monitoringstack:


